/* valaoop.c generated by valac 0.56.16, the Vala compiler
 * generated from valaoop.vala, do not modify */

/* Clase base*/

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_DROID (droid_get_type ())
#define DROID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DROID, Droid))
#define DROID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DROID, DroidClass))
#define IS_DROID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DROID))
#define IS_DROID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DROID))
#define DROID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DROID, DroidClass))

typedef struct _Droid Droid;
typedef struct _DroidClass DroidClass;
typedef struct _DroidPrivate DroidPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ParamSpecDroid ParamSpecDroid;

#define TYPE_AQUA_DROID (aqua_droid_get_type ())
#define AQUA_DROID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AQUA_DROID, AquaDroid))
#define AQUA_DROID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_AQUA_DROID, AquaDroidClass))
#define IS_AQUA_DROID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AQUA_DROID))
#define IS_AQUA_DROID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_AQUA_DROID))
#define AQUA_DROID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AQUA_DROID, AquaDroidClass))

typedef struct _AquaDroid AquaDroid;
typedef struct _AquaDroidClass AquaDroidClass;
typedef struct _AquaDroidPrivate AquaDroidPrivate;

struct _Droid {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DroidPrivate * priv;
	gint x;
	gint y;
};

struct _DroidClass {
	GTypeClass parent_class;
	void (*finalize) (Droid *self);
	void (*move) (Droid* self, gint x, gint y);
};

struct _DroidPrivate {
	gchar* _name;
};

struct _ParamSpecDroid {
	GParamSpec parent_instance;
};

struct _AquaDroid {
	Droid parent_instance;
	AquaDroidPrivate * priv;
};

struct _AquaDroidClass {
	DroidClass parent_class;
};

struct _AquaDroidPrivate {
	gint depth;
};

static gint Droid_private_offset;
static gpointer droid_parent_class = NULL;
static gint AquaDroid_private_offset;
static gpointer aqua_droid_parent_class = NULL;

VALA_EXTERN gpointer droid_ref (gpointer instance);
VALA_EXTERN void droid_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_droid (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags);
VALA_EXTERN void value_set_droid (GValue* value,
                      gpointer v_object);
VALA_EXTERN void value_take_droid (GValue* value,
                       gpointer v_object);
VALA_EXTERN gpointer value_get_droid (const GValue* value);
VALA_EXTERN GType droid_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Droid, droid_unref)
VALA_EXTERN void droid_move (Droid* self,
                 gint x,
                 gint y);
VALA_EXTERN Droid* droid_new (const gchar* n);
VALA_EXTERN Droid* droid_construct (GType object_type,
                        const gchar* n);
VALA_EXTERN void droid_set_name (Droid* self,
                     const gchar* value);
static void droid_real_move (Droid* self,
                      gint x,
                      gint y);
VALA_EXTERN const gchar* droid_get_name (Droid* self);
static void droid_finalize (Droid * obj);
static GType droid_get_type_once (void);
VALA_EXTERN GType aqua_droid_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AquaDroid, droid_unref)
VALA_EXTERN AquaDroid* aqua_droid_new (const gchar* n,
                           gint md);
VALA_EXTERN AquaDroid* aqua_droid_construct (GType object_type,
                                 const gchar* n,
                                 gint md);
static void aqua_droid_real_move (Droid* base,
                           gint x,
                           gint y);
static void aqua_droid_finalize (Droid * obj);
static GType aqua_droid_get_type_once (void);

static inline gpointer
droid_get_instance_private (Droid* self)
{
	return G_STRUCT_MEMBER_P (self, Droid_private_offset);
}

Droid*
droid_construct (GType object_type,
                 const gchar* n)
{
	Droid* self = NULL;
	g_return_val_if_fail (n != NULL, NULL);
	self = (Droid*) g_type_create_instance (object_type);
	droid_set_name (self, n);
	return self;
}

Droid*
droid_new (const gchar* n)
{
	return droid_construct (TYPE_DROID, n);
}

static void
droid_real_move (Droid* self,
                 gint x,
                 gint y)
{
	self->x = x;
	self->y = y;
}

void
droid_move (Droid* self,
            gint x,
            gint y)
{
	DroidClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = DROID_GET_CLASS (self);
	if (_klass_->move) {
		_klass_->move (self, x, y);
	}
}

const gchar*
droid_get_name (Droid* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}

void
droid_set_name (Droid* self,
                const gchar* value)
{
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp0_;
}

static void
value_droid_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_droid_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		droid_unref (value->data[0].v_pointer);
	}
}

static void
value_droid_copy_value (const GValue* src_value,
                        GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = droid_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_droid_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_droid_collect_value (GValue* value,
                           guint n_collect_values,
                           GTypeCValue* collect_values,
                           guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Droid * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = droid_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_droid_lcopy_value (const GValue* value,
                         guint n_collect_values,
                         GTypeCValue* collect_values,
                         guint collect_flags)
{
	Droid ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = droid_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_droid (const gchar* name,
                  const gchar* nick,
                  const gchar* blurb,
                  GType object_type,
                  GParamFlags flags)
{
	ParamSpecDroid* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_DROID), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_droid (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_DROID), NULL);
	return value->data[0].v_pointer;
}

void
value_set_droid (GValue* value,
                 gpointer v_object)
{
	Droid * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_DROID));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_DROID));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		droid_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		droid_unref (old);
	}
}

void
value_take_droid (GValue* value,
                  gpointer v_object)
{
	Droid * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_DROID));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_DROID));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		droid_unref (old);
	}
}

static void
droid_class_init (DroidClass * klass,
                  gpointer klass_data)
{
	droid_parent_class = g_type_class_peek_parent (klass);
	((DroidClass *) klass)->finalize = droid_finalize;
	g_type_class_adjust_private_offset (klass, &Droid_private_offset);
	((DroidClass *) klass)->move = (void (*) (Droid*, gint, gint)) droid_real_move;
}

static void
droid_instance_init (Droid * self,
                     gpointer klass)
{
	self->priv = droid_get_instance_private (self);
	self->ref_count = 1;
}

static void
droid_finalize (Droid * obj)
{
	Droid * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DROID, Droid);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->_name);
}

static GType
droid_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_droid_init, value_droid_free_value, value_droid_copy_value, value_droid_peek_pointer, "p", value_droid_collect_value, "p", value_droid_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (DroidClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) droid_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Droid), 0, (GInstanceInitFunc) droid_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType droid_type_id;
	droid_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Droid", &g_define_type_info, &g_define_type_fundamental_info, 0);
	Droid_private_offset = g_type_add_instance_private (droid_type_id, sizeof (DroidPrivate));
	return droid_type_id;
}

GType
droid_get_type (void)
{
	static volatile gsize droid_type_id__once = 0;
	if (g_once_init_enter (&droid_type_id__once)) {
		GType droid_type_id;
		droid_type_id = droid_get_type_once ();
		g_once_init_leave (&droid_type_id__once, droid_type_id);
	}
	return droid_type_id__once;
}

gpointer
droid_ref (gpointer instance)
{
	Droid * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
droid_unref (gpointer instance)
{
	Droid * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		DROID_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

static inline gpointer
aqua_droid_get_instance_private (AquaDroid* self)
{
	return G_STRUCT_MEMBER_P (self, AquaDroid_private_offset);
}

AquaDroid*
aqua_droid_construct (GType object_type,
                      const gchar* n,
                      gint md)
{
	AquaDroid* self = NULL;
	g_return_val_if_fail (n != NULL, NULL);
	self = (AquaDroid*) droid_construct (object_type, n);
	self->priv->depth = md;
	return self;
}

AquaDroid*
aqua_droid_new (const gchar* n,
                gint md)
{
	return aqua_droid_construct (TYPE_AQUA_DROID, n, md);
}

static void
aqua_droid_real_move (Droid* base,
                      gint x,
                      gint y)
{
	AquaDroid * self;
	self = (AquaDroid*) base;
	((Droid*) self)->x = x / 2;
	((Droid*) self)->y = y / 2;
}

static void
aqua_droid_class_init (AquaDroidClass * klass,
                       gpointer klass_data)
{
	aqua_droid_parent_class = g_type_class_peek_parent (klass);
	((DroidClass *) klass)->finalize = aqua_droid_finalize;
	g_type_class_adjust_private_offset (klass, &AquaDroid_private_offset);
	((DroidClass *) klass)->move = (void (*) (Droid*, gint, gint)) aqua_droid_real_move;
}

static void
aqua_droid_instance_init (AquaDroid * self,
                          gpointer klass)
{
	self->priv = aqua_droid_get_instance_private (self);
}

static void
aqua_droid_finalize (Droid * obj)
{
	AquaDroid * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_AQUA_DROID, AquaDroid);
	DROID_CLASS (aqua_droid_parent_class)->finalize (obj);
}

static GType
aqua_droid_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AquaDroidClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) aqua_droid_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AquaDroid), 0, (GInstanceInitFunc) aqua_droid_instance_init, NULL };
	GType aqua_droid_type_id;
	aqua_droid_type_id = g_type_register_static (TYPE_DROID, "AquaDroid", &g_define_type_info, 0);
	AquaDroid_private_offset = g_type_add_instance_private (aqua_droid_type_id, sizeof (AquaDroidPrivate));
	return aqua_droid_type_id;
}

GType
aqua_droid_get_type (void)
{
	static volatile gsize aqua_droid_type_id__once = 0;
	if (g_once_init_enter (&aqua_droid_type_id__once)) {
		GType aqua_droid_type_id;
		aqua_droid_type_id = aqua_droid_get_type_once ();
		g_once_init_leave (&aqua_droid_type_id__once, aqua_droid_type_id);
	}
	return aqua_droid_type_id__once;
}

